### ISSUE TITLE
Add more weather data

### ISSUE THREAD

**Issue by zadilkhwaja** [zadilkhwaja/Weather_App_Django#1]
Currently, this weather app displays information about temperature when the user searches for the city.
We would also like to display information about pressure, humidity and country when the user searches for a city.
- [ ] Pressure
- [ ] Humidity
- [ ] Country

Fell free to pick any and comment below on what you are going to work on!
You may also add any additional information if you would like.
If you are stuck don't hesitate to ask questions!

**Comment by Mannuel25** [comment]
I'd love to work on this too. If I may ask, do you have any format/structure as to how the data will be displayed in template?

**Comment by zadilkhwaja** [comment]
Yes, go ahead! At present I do not have any format for styling and UI. You can check the screenshots in readme file on how the temprature data is being displayed. I think at present we can just display data one below the other. If you want you could also work on improving the structure of the page first. Thanks!

**Comment by Mannuel25** [comment]
Okay :+1:
