### ISSUE TITLE
Display Temperature in Celsius

### ISSUE THREAD

**Issue by zadilkhwaja** [zadilkhwaja/Weather_App_Django#2]
By default the temperature of all cities is displayed in Kelvin. We want to display in Celsius.
(Optional): Provide the user an option to either view in K or *C.

If you are stuck don't hesitate to ask questions!

**Comment by Mannuel25** [comment]
Hello @zadilkhwaja I'd love to work on this.


I've a suggestion, what if we convert the Kelvin to celcius then add it to the temperature generated .
For example: 298.04K / 24.89°C

OR

We give them the option to select the unit they want the temperature to be displayed in.

Which one should we go for?

**Comment by zadilkhwaja** [comment]
Great! Either way is fine. Go ahead with whichever option you're comfortable working on.

**Comment by Mannuel25** [comment]
> Great! Either way is fine. Go ahead with whichever option you're comfortable working on.

Okay, thanks
